 export const doctorsData = [
    {
      id: 1,
      sex:"Male",
      specialty: "Endocrinologist",
      experience: "10 years",
      location: "Homs",
      phone: "092345678",
      rating: 4.8,
      patients: 1200,
      workingHours: "9 AM - 5 PM",
      condition: "diabetes",
      description: "Expert in diabetes treatment and insulin therapy.",
      education: "Damascus University",
      languages: ["Arabic", "English"],
    },
  
    {
      id: 2,
      Sex:"Feamle",
      specialty: "Endocrinologist",
      experience: "7 years",
      location: "Homs",
      phone: "0991244417",
      rating: 4.6,
      patients: 850,
      workingHours: "10 AM - 4 PM",
      condition: "diabetes",
      description: "Specialist in hormonal disorders.",
      education: "Aleppo University",
      languages: ["Arabic"],
    },
  
    {
      id: 3,
      sex:"Female",
      specialty: "Hematologist",
      experience: "9 years",
      location: "Homs",
      phone: "0994960945",
      rating: 4.7,
      patients: 950,
      workingHours: "8 AM - 3 PM",
      condition: "anemia",
      description: "Specialist in anemia and blood diseases.",
      education: "Damascus University",
      languages: ["Arabic", "English"],
    },
  
    {
      id: 4,
     sex:"Male",
      specialty: "Hematologist",
      experience: "6 years",
      location: "Homs",
      phone: "0944444444",
      rating: 4.5,
      patients: 700,
      workingHours: "11 AM - 6 PM",
      condition: "anemia",
      description: "Experienced in treating iron deficiency.",
      education: "Tishreen University",
      languages: ["Arabic"],
    },
  
    {
      id: 5,
      Sex: "Female",
      specialty: "Nutritionist",
      experience: "5 years",
      location: "Homs",
      phone: "0955555555",
      rating: 4.4,
      patients: 600,
      clinic: "Healthy Life Center",
      workingHours: "9 AM - 2 PM",
      condition: "all",
      description: "Provides healthy diet plans.",
      education: "Damascus University",
      languages: ["Arabic", "English"],
    },
  
    {
      id: 6,
      Sex:"Female",
      specialty: "Nutritionist",
      experience: "8 years",
      location: "Homs",
      phone: "0966666666",
      rating: 4.9,
      patients: 1400,
      workingHours: "10 AM - 6 PM",
      condition: "all",
      description: "Expert in weight loss and muscle gain.",
      education: "Aleppo University",
      languages: ["Arabic", "English"],
    
    },
]